name: Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit
        pip install --trusted-host pypi.python.org -r requirements.txt

    - name: Run Streamlit App
      env:
        GOOGLE_PALM2: ${{ secrets.GOOGLE_PALM2}}
      run: |
        streamlit run streamlit_app.py
